apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    name: node-app-pod
    app: demo-node-app
spec:
  containers:
  - name: node-app
    image: haisrig/demo
    ports:
         - containerPort: 8080