apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: demo-node-app
spec:
  ports:
  - port: 8081
    targetPort: 8080
  type: LoadBalancer
  selector:
     name: node-app-pod
     app: demo-node-app